// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;

namespace PhillyCrime.Models
{
	// Generated by Xamasoft JSON Class Generator
	// http://www.xamasoft.com/json-class-generator

	using System;
	using System.Collections.Generic;
	using System.ComponentModel;
	using Newtonsoft.Json;
	using Newtonsoft.Json.Linq;

	[Flags]
	public enum Filter
	{
		Nothing = 0,
		Homicide = 1,
		Assault = 2,
		Burglary = 4,
		Robbery = 8,
		Theft = 16,
		Rape = 32,
		Vehicle = 64,
		Gun = 128,
		Prostition = 256,
		Other = 512
	}

	public enum CrimeType
	{
		Nothing = 0,
		Homicide = 1,
		Assault = 2,
		Burglary = 3,
		Robbery = 4,
		Theft = 5,
		Rape = 6,
		Narcotics = 7,
		StolenVehicle = 8,
		TheftFromAuto = 9,
		VehicleRecovery = 10,
		CriminalMischief = 11,
		DUI = 12,
		Arson = 13,
		Prostitution = 14,
		Gun = 15,
		Prostition = 16,
		OtherSexAssault = 17,
		Fraud = 18,
		Other = 19
	}

	public class Area
	{
		public PoliceDistrict PoliceDistrict { get; set; }
		public Neighborhood Neighborhood { get; set; }
	}

	public class Neighborhood : INotifyPropertyChanged
	{
		string _name;
		public string Name
		{
			get { return _name; }
			set
			{
				if (_name != value)
					_name = value;
				OnPropertyChanged("Name");
			}
		}

		int _id;
		public int ID
		{
			get { return _id; }
			set
			{
				if (_id != value)
					_id = value;
				OnPropertyChanged("ID");
			}
		}

		bool _selected;
		public bool Selected
		{
			get { return _selected; }
			set
			{
				if (_selected != value)
					_selected = value;
				OnPropertyChanged("Selected");
			}
		}

		public event PropertyChangedEventHandler PropertyChanged;
		void OnPropertyChanged(string propertyName)
		{
			PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
		}
	}

	public class PoliceDistrict
	{
		public string District { get; set; }
		public string PSA { get; set; }
	}

	public class FullCrimeReport
	{
		public string DCN { get; set; }
		public PhillyCrime.Models.Crime FullCrimeDetail { get; set; }
		public PhillyCrime.Models.Arrest[] FullArrestDetails { get; set; }
	}

	public class crime_notification
	{
		public string DeviceToken { get; set; }
		public int DeviceType { get; set; }
		public double Longitude { get; set; }
		public double Latitude { get; set; }
	}

	public class Crime
	{
		public int ID { get; set; }
		public string DC_DIST { get; set; }
		public string SECTOR { get; set; }
		public DateTime? DISPATCH_DATE_TIME { get; set; }
		public System.DateTime? DISPATCH_DATE { get; set; }
		public System.DateTime? DISPATCH_TIME { get; set; }
		public string HOUR { get; set; }
		public string DC_KEY { get; set; }
		public string LOCATION_BLOCK { get; set; }
		public string UCR_GENERAL { get; set; }
		public int? OBJECTID { get; set; }
		public string TEXT_GENERAL_CODE { get; set; }
		public string POINT_X { get; set; }
		public string POINT_Y { get; set; }
		public string SHAPE { get; set; }
		public string NEIGHBORHOOD { get; set; }
		public string LAST_UPDATED_STR { get; set; }
		public DateTime? LAST_UPDATED { get; set; }
	}

	public class Arrest
	{
		public int ID { get; set; }
		public int? SimpleCaseNumber { get; set; }
		public string CaseNumber { get; set; }
		public string Defendant { get; set; }
		public string DefendantZip { get; set; }
		public string DCN { get; set; }
		public string PoliceDistrict { get; set; }
		public string ArrestingOfficer { get; set; }
		public string DateOfBirth { get; set; }
		public string PrimaryCharge { get; set; }
		public DateTime? DateArrested { get; set; }
		public string CaseYear { get; set; }
		public string Bail { get; set; }
		public string BailDate { get; set; }
		public string Url { get; set; }
		public DateTime? SuppressedExpires { get; set; }
		public string SuspendCode { get; set; }
	}

	public class CrimeReport
	{

		public string DCN { get; set; }
		public DateTime? Occurred { get; set; }
		public double Longitude { get; set; }
		public double Latitutde { get; set; }
		public string Address { get; set; }
		public CrimeType Type { get; set; }
		public string Title { get; set; }
		public string Code { get; set; }
		public int ArrestCount { get; set; }
	}

}